### ISSUE TITLE
Best PDF reader works with fax4J

### ISSUE THREAD

**Issue by AnthonySTHO** [sagiegurari/fax4j#13]
Since Adobe Reader requires to pop up its UI during the fax process scheduled in windows task scheduler, the scheduled task requires user to login windows when the job is executed. Is there any suggestion for other 3rd parties PDF reader working with fax4J which allows the program to be executed even the user account running the job has not logged in Windows? I have tested foxit reader version 6.22, PDF-XChange PDF Viewer version 2.5.322 in Windows 10, non of them works.

**Comment by sagiegurari** [comment]
as far as i remember, foxit reader was really good and didn't popup any UI.
acrobat always popped up some UI which made it unusable.
10 years later... hard to say which one is the best as i'm not using and really hard to maintain it at this point.
