### ISSUE TITLE
fax4J in .Net

### ISSUE THREAD

**Issue by deadmann** [sagiegurari/fax4j#2]
Dear sir,

i went through Converting fax4j to .net library using IKVM 7.2.
but when i launch my application, it keep on telling me that the properties file doesn't exist, how can i avoid this error?

thank you,
regarded by Hassan F.

**Comment by sagiegurari** [comment]
It needs the fax4j.properties file found inside the fax4j jar
I guess that's the one that is missing and gives you the error.

I also got a jni layer to talk to win32 fax api (it is one of the many built in SPIs), and I guess if you are in .net, you should provide a better implementation instead of doing jni. afterall, you have direct access to win32 apis via .net if i'm not wrong.

**Comment by deadmann** [comment]
Today my boss asked  me,  look for any possible way to receive a fax,  so I searched,  and look in places like code project and etc. I didn't see anything for free,  and one of them was c++ library.  Then I though of,  if I should go through c++, I prefer java, so I searched,  and found you. I later found several link that I didn't still tired. 

I also find a properties file. In the full version library,  which contains many lines of code,  I did filestream to inject it to your main class,  which result in same error,  
I did create a properties file,  and called load method,  then pass null, property to the factory.

**Comment by sagiegurari** [comment]
fax4j is a fax client library which enables to send faxes, not receive.
so I'm not sure it is the right lib for you.

**Comment by sagiegurari** [comment]
I think using win32 api via .net makes more sense for you and if i'm not wrong, you have ability to receive fax messages as well (could be wrong):
https://msdn.microsoft.com/en-us/library/windows/desktop/ms692803(v=vs.85).aspx

**Comment by deadmann** [comment]
Thanks man, i didn't know i cant receive fax with it, as it was suppose to be the first step...
and thanks for the library.
isn't win32 the C++ lib, which require knowledge of the exist method inside the lib to call them using extern or something like that...

**Comment by sagiegurari** [comment]
Didn't understand the question however I integrated with that lib in fax4j c++ code so you can check that as an example.

**Comment by deadmann** [comment]
i somehow manage to understand when a fax come, but since i couldn't find the binary, i read from archive... using C#, and faxcomexlib
