### ISSUE TITLE
VBS SPI cint overflow

### ISSUE THREAD

**Issue by MarkusBretterbauer** [sagiegurari/fax4j#6]
Hi,

I had a problem that i couldn't observe the faxjobstatus of a submitted fax. The fax got an id over 60000 assigned and therefore caused cint in the .vbs-script "win2k_get_fax_job_status.vbs" to overflow. Maybe because I work in an 64bit (Windows) environment this ids get so big.

After I changed "cint" to "clng" everything worked (in my case) fine. I would really appreciate it if this change (and maybe further changes because of this - i don't know) goes into the library! :)

**Comment by sagiegurari** [comment]
Thanks, I'll push that change, but just quick question, vbscript for a long time is not really safe to invoke and windows stops you with a ton of warnings (it worked fine in the old days of win2k :)), so by default I point to the windows spi and not vbs.
is the windows spi not working for you? its faster, and has more support.

**Comment by MarkusBretterbauer** [comment]
Thank you!

The windows spi did not work for me. I always got the error-message "access denied", altough the hostname was the same as for vbs. Maybe it is just a configuration issue, but i wasn't able to solve it. So i stayed with the vbs spi since (almost ;) ) everything worked fine :).

**Comment by sagiegurari** [comment]
Ok. I hope to publish a new version today/tomorrow

**Comment by sagiegurari** [comment]
Done, please confirm.

**Comment by sagiegurari** [comment]
@MarkusBretterbauer can you please confirm it solves your issue?

**Comment by MarkusBretterbauer** [comment]
Thank you!
