### ISSUE TITLE
Fax4j works in Eclipse simulation but not in tomcat

### ISSUE THREAD

**Issue by andreasinspire** [sagiegurari/fax4j#7]
Sagie thanks a lot for the swift response
As requested a new issue is raised
Below is the log that I extracted as per your request (attached)
[traces.txt](https://github.com/sagiegurari/fax4j/files/1544837/traces.txt)

**Comment by sagiegurari** [comment]
ok, so it is not one of the documented errors thrown by windows FaxSendDocument which makes it pretty hard to debug.
So lets try to understand how it is different when invoked in your eclipse or in your tomcat runtime.
1. is it running on same machine
2. is the process owner same user? in eclipse it is the user you login the windows with, but how is the tomcat invoked? via windows server maybe?
3. is the same file faxed ok via eclipse but not via tomcat or different files?
4. can you run with debug when invoking via eclipse and lets see if there are differences there. maybe post it here as well.

**Comment by andreasinspire** [comment]
Thanks 
It is the same machine
Eclipse is run by me (am an admin on the laptop). TOMCAT is run as a service.
The same file is faxed ok when sent from Eclipse
Below is the trace. I see problems but the fax is in the output queue of windows fax and scan 
[eclipsetrace.txt](https://github.com/sagiegurari/fax4j/files/1544917/eclipsetrace.txt)

**Comment by sagiegurari** [comment]
ok so when java is executed as a service, it has less permissions.
its actually a known issue that I saw many times before from people.
I believe it is possible to define the user of the service, so try to define your user instead of the default local user which doesn't have the permissions to invoke the fax submision in windows.

I used to have the answers in the sourceforge forums, but I deleted all of them, sorry.

**Comment by andreasinspire** [comment]
I changed the user to be my user via changing the logon credentials of the service. It fails again. Some additional logs
[withadmin.txt](https://github.com/sagiegurari/fax4j/files/1545133/withadmin.txt)

**Comment by andreasinspire** [comment]
I run c:\apache-tomcat-8.0.14\temp\fax4j_0.44.1\fax4j.exe" -action "submit" -server "AndreasYoga" -target_address "22833616" -sender_name "Despo Lab" -file "C:\lab\reports\lab_micro\results_11124.pdf" from the command prompt and it works.

**Comment by sagiegurari** [comment]
I think its same issue. user for the service doesn't have permission to submit a fax and windows rejects it.
thats why it works for you, but doesn't in the service.
maybe try NetworkService as user account: https://msdn.microsoft.com/en-us/library/windows/desktop/ms684272(v=vs.85).aspx
It was many years ago, but I do remember people solving it by setting to a user with permisssions. I'm just not familiar enough with the details, but lets see if this solves it.

**Comment by andreasinspire** [comment]
Sagie first THANKS for the immediate support. Great professionalism. 
Problem solved. I was starting TOMCAT as a service and I was not sure how to define the security policies to grant AllPermission to the folder where fax4j jar was. I stopped using the service and I start TOMCAT with catalina start -security. This reads the catalina.policy file that has the aforementioned security policy in it. Again thanks for everything

**Comment by sagiegurari** [comment]
So issue resolved? great news.
