### ISSUE TITLE
DONE status for WindowsFaxClientSpi

### ISSUE THREAD

**Issue by mastermind323** [sagiegurari/fax4j#8]
@sagiegurari , Does the WindowsFaxClientSpi fire an event on the successful completion of a fax? 
I do not see a status for DONE in the FaxJobStatus enum.

**Comment by sagiegurari** [comment]
Once its done, its out of the queue and I can't find it anymore so it becomes unknown actually.
if its stuck on some error it will be error or pending.
So you can use the fax monitor event and than when it is status back to unknown you can assume its done.
Naturally I'm answering on something developed initially 9 years ago, so... you will have to test that I remember correctly :)

**Comment by mastermind323** [comment]
Ok. You are correct, the status is changed to unknown when completed. Thanks.
