### ISSUE TITLE
Can't get windows 7 to submit fax job

### ISSUE THREAD

**Issue by stevmon** [sagiegurari/fax4j#9]
I am sorry if this has already been addressed but I could not find it.

I have been using fax4j on Windows 2000 and XP systems for some time now. Works great! Thanks!

Finally we are moving the clients to Windows 7. Strange thing is that the application works fine in Windows Server 2008 R2 environment (with development tools installed) but does not like the Windows 7 Professional environment. I get an error when submitting a fax there. I thought it might be a rights/privileges issue but when I create a VB app to submit a fax it works fine.

I have debugging set and the error occurs when trying to do the  submitToFaxJobNative method. It seems to convert all of the strings and the final message before failure. Snip from the log:

Priority: HIGH_PRIORITY
Target Address: 1605366XXXX
Target Name: Dr Stev
Sender Name: Dr Stev Local
Sender Fax Number: 1605366XXXX
Sender Email: stevmon1@xxx.xxx.xxx
Properties:
{}
[fax4j-native][DEBUG] Debug mode enabled.
[fax4j-native][DEBUG] Invoking JNI submitFaxJobNative
[fax4j-native][DEBUG] Converting java data types to C data types.
[fax4j-native][DEBUG] Converting java char array to string.
[fax4j-native][DEBUG] 1605xxxxxxx
[fax4j-native][DEBUG] Converting java char array to string.
[fax4j-native][DEBUG] Dr Stev
[fax4j-native][DEBUG] Converting java char array to string.
[fax4j-native][DEBUG] Dr Stev Local
[fax4j-native][DEBUG] Converting java char array to string.
[fax4j-native][DEBUG] C:\Installs\Exio\ExioFax\ExioFaxTest\000000000072FaxDocument.pdf
[fax4j-native][DEBUG] Converting java char array to string.
[fax4j-native][DEBUG]
[fax4j-native][DEBUG] Invoking submitFaxJobNative
[fax4j-native][DEBUG] Connecting to fax server.
[fax4j-native][DEBUG] Initializing fax job parameters.
[fax4j-native][DEBUG] Releasing cover page info.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x77225d89, pid=1016, tid=2316
#
# JRE version: 6.0_27-b07
# Java VM: Java HotSpot(TM) Client VM (20.2-b06 mixed mode, sharing windows-x86 )
# Problematic frame:
#
[error occurred during error reporting (printing problematic frame), id 0xc0000005]

[error occurred during error reporting , id 0xc0000005]

I have been trying to figure this out for days and have not been able to make progress. I would not contact otherwise. Any Ideas? I compiled the fax4j.exe and fax4j.dll on the Windows Professional system using Visual Studio C++ 2010 Express and the communication between the Java and the fax4j native applications seems to be working fine.

Thanks for any guidance you can give.

**Comment by sagiegurari** [comment]
sorry for the late reply.

based on the log you provided it is failing in one of those 2 lines:

```cpp
faxCoverPageInfo->SizeOfStruct=sizeof(FAX_COVERPAGE_INFO);
FaxFreeBuffer(faxCoverPageInfo);
```

which to me means that the fax component in the windows installation is corrupted or something.
its really just a guess as it should not fail on it and its pretty much static code of releasing an unneeded component.

I do know of people who ran this on windows 7 but i admit that I have not ran this for many years now and its hard for me to really give good support for the project.

you could try to create a simple cpp main with the following code and see if it fails as well

```cpp
PFAX_JOB_PARAM faxJobParameters;
PFAX_COVERPAGE_INFO faxCoverPageInfo;
printf("%s\n","Initializing fax job parameters.");
fflush(stdout);
result=FaxCompleteJobParams(&faxJobParameters,&faxCoverPageInfo);
if(result==0)
{
	response.errorCode=GetLastError();
	response.errorMessage="Unable to initialize fax job parameters, closing fax server connection.";

	logDebug(response.errorMessage);
	
	//close connection to fax server
	FaxClose(faxServerHandle);
	
	lastErrorMessage=response.errorMessage;

	return response;
}

//release cover page info
printf("%s\n","getting size of cover info...");
fflush(stdout);
faxCoverPageInfo->SizeOfStruct=sizeof(FAX_COVERPAGE_INFO);
printf("%s\n","Free fax buffer...");
fflush(stdout);
FaxFreeBuffer(faxCoverPageInfo);
```
